export default {
    LOGIN: 'Login', 
    DASHBOARD: 'Dashboard', 
    TRANSACTIONS: 'Transactions', 
    CREATE_TRANSACTION: 'Create Transaction', 
    DETAIL_TRANSACTION: 'Detail Transaction', 
    EMPLOYEE: 'Employee', 
    CREATE_EMPLOYEE: 'Create Employee', 
    DETAIL_EMPLOYEE: 'Detail Employee', 
    ONBOARDING: 'Onboarding',
    BOOK: 'Book',
    SETTING: 'Setting',
    ACTIVITY: 'Activity',
    CREATE_BOOK: 'Create Book',
}